services:

  fastapi-app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./app:/app  
    depends_on:
      - db  
      - redis
    environment:
      - DB_ASYNC_CONNECTION_STR=${DB_ASYNC_CONNECTION_STR}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    env_file:
      - .env
  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env  
  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"    
    command: redis-server  
volumes:
  postgres_data: